### ISSUE TITLE
Character not showing

### ISSUE THREAD

**Issue by Igorzcech** [DokusCore/DokusCore#2]
Hello in the company. I have a problem. After creating a character, I can't see it. I have a physical figure in my mind, I can dress for it, but not the figure. Otherwise, a great project, he just gave it away. I have all the repositories up to date.
![RedM™ by Cfx re - Pochvanic 25 09 2022 8_19_43](https://user-images.githubusercontent.com/55141417/192134520-9d081e27-9f1e-484c-b4da-df1129d49a4e.png)

**Comment by DevDokus** [comment]
Hey @Igorzcech 

This issue is when you do not select a torso, legs, head and eyes in the character creator. The default character you see is just a NPC that you need to change to you likings, if you just keep clicking next without selecting your values, no skin values are saved to the database thus the core being unable to load your skin. I would recommend making a new characters ( first delete your old character info from all tables), or create a new character and then copy the skin from this character to your main, then you can delete your second character. 

This issue was fixed before and came back in one of the later version, we will have a look at it to fix it. Thanks for your report!

**Comment by DevDokus** [comment]
Issue is fixed with the latest updates
